Repository TheDragonCode/laravel-route-names, pull requests merged in 2025-04, with the labels that each got.

#31 Added tests for PR
  .github/workflows/phpunit.yml
Labels: skip-changelog

#32 Update `README.md`
  README.md
Labels: skip-changelog

#33 Update README.md
  README.md
Labels: skip-changelog

#34 The removal of `Application.php` was canceled
  README.md
  src/Application.php
Labels: fix

#30 Extend router and remove `RoutingServiceProvider`
  src/Providers/RoutingServiceProvider.php
  src/ServiceProvider.php
  tests/TestCase.php
Labels: minor

#35 Removed useless file. Again 😅
  README.md
  src/Application.php
Labels: fix

#38 Unsupporting older versions of Laravel
  .gitattributes
  .github/workflows/phpunit.yml
  composer.json
  phpunit.php
  phpunit.xml
  src/Helpers/Action.php
  src/Routing/Route.php
Labels: removed

#39 Added tests workspace and drop Laravel 10 support
  .gitattributes
  .github/workflows/phpunit.yml
  README.md
  composer.json
  src/Application.php
  src/Providers/RoutingServiceProvider.php
  testbench.yaml
  tests/Concerns/Routes.php
  tests/Http/Controllers/ApiResourceController.php
  tests/Http/Controllers/Controller.php
  tests/Http/Controllers/WebResourceController.php
  tests/Routes/ResourcesTest.php
  tests/TestCase.php
  workbench/app/Http/Controllers/ApiController.php
  workbench/app/Http/Controllers/SomeController.php
  workbench/app/Http/Controllers/WebController.php
  workbench/app/Models/.gitkeep
  workbench/app/Models/User.php
  workbench/bootstrap/app.php
  workbench/bootstrap/cache/.gitignore
  workbench/bootstrap/providers.php
  workbench/config/view.php
  workbench/resources/views/.gitkeep
  workbench/routes/api.php
  workbench/routes/basic.php
  workbench/routes/collision.php
  workbench/routes/extended.php
  workbench/routes/mixed_case.php
  workbench/routes/parameters.php
  workbench/routes/protected.php
  workbench/storage/framework/views/.gitignore
  workbench/storage/logs/.gitignore
Labels: minor

#40 Drop `fig/http-message-util`
  composer.json
  src/Helpers/Action.php
Labels: removed

#41 A little code cleanup
  src/Routing/Route.php
  src/ServiceProvider.php
Labels: minor
